export type Module = {
  id: string;
  title: string;
  imageId: string;
  pdfUrl?: string;
};

export const modules: Module[] = [
  { id: 'genesis', title: 'Gênesis', imageId: 'genesis', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.5946705890976148.pdf' },
  { id: 'jo', title: 'Jó', imageId: 'jo', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.6391026448671588.pdf' },
  { id: 'exodo', title: 'Êxodo', imageId: 'exodo', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.3033526757397845.pdf' },
  { id: 'levitico', title: 'Levítico', imageId: 'levitico', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.37906283702767407.pdf' },
  { id: 'numeros', title: 'Números', imageId: 'numeros', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.925013572783077.pdf' },
  { id: 'deuteronomio', title: 'Deuteronômio', imageId: 'deuteronomio', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.7725746038493831.pdf' },
  { id: 'josue', title: 'Josué', imageId: 'josue', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.5081917237726271.pdf' },
  { id: 'juizes', title: 'Juízes', imageId: 'juizes', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.7434052852617942.pdf' },
  { id: 'rute', title: 'Rute', imageId: 'rute', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.5763680969187531.pdf' },
  { id: '1-samuel', title: '1 Samuel', imageId: '1-samuel', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.43368864218785086.pdf' },
  { id: '2-samuel', title: '2 Samuel', imageId: '2-samuel', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.6627585696621219.pdf' },
  { id: '1-reis', title: '1 Reis', imageId: '1-reis', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.6894252123406397.pdf' },
  { id: '2-reis', title: '2 Reis', imageId: '2-reis', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.2460320432969223.pdf' },
  { id: '1-cronicas', title: '1 Crônicas', imageId: '1-cronicas', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.828932636547315.pdf' },
  { id: '2-cronicas', title: '2 Crônicas', imageId: '2-cronicas', pdfUrl: 'https://kdloteojnkcjblhoirea.supabase.co/storage/v1/object/public/public-files/0.664730505501718.pdf' },
  { id: 'salmos', title: 'Salmos', imageId: 'salmos' },
  { id: 'proverbios', title: 'Provérbios', imageId: 'proverbios' },
  { id: 'eclesiastes', title: 'Eclesiastes', imageId: 'eclesiastes' },
  { id: 'canticos', title: 'Cânticos', imageId: 'canticos' },
  { id: 'isaias', title: 'Isaías', imageId: 'isaias' },
  { id: 'oseias', title: 'Oséias', imageId: 'oseias' },
  { id: 'amos', title: 'Amós', imageId: 'amos' },
  { id: 'jonas', title: 'Jonas', imageId: 'jonas' },
  { id: 'jeremias', title: 'Jeremias', imageId: 'jeremias' },
  { id: 'lamentacoes', title: 'Lamentações', imageId: 'lamentacoes' },
  { id: 'sofonias', title: 'Sofonias', imageId: 'sofonias' },
  { id: 'naum', title: 'Naum', imageId: 'naum' },
  { id: 'habacuque', title: 'Habacuque', imageId: 'habacuque' },
  { id: 'daniel', title: 'Daniel', imageId: 'daniel' },
  { id: 'ezequiel', title: 'Ezequiel', imageId: 'ezequiel' },
  { id: 'obadias', title: 'Obadias', imageId: 'obadias' },
  { id: 'ageu', title: 'Ageu', imageId: 'ageu' },
  { id: 'zacarias', title: 'Zacarias', imageId: 'zacarias' },
  { id: 'malaquias', title: 'Malaquias', imageId: 'malaquias' },
  { id: 'nt', title: 'NT (Novo Testamento)', imageId: 'nt' },
  { id: 'mateus', title: 'Mateus', imageId: 'mateus' },
  { id: 'marcos', title: 'Marcos', imageId: 'marcos' },
  { id: 'lucas', title: 'Lucas', imageId: 'lucas' },
  { id: 'joao', title: 'João', imageId: 'joao' },
  { id: 'atos', title: 'Atos', imageId: 'atos' },
  { id: 'tiago', title: 'Tiago', imageId: 'tiago' },
  { id: '1-tessalonicenses', title: '1 Tessalonicenses', imageId: '1-tessalonicenses' },
  { id: '2-tessalonicenses', title: '2 Tessalonicenses', imageId: '2-tessalonicenses' },
  { id: '1-corintios', title: '1 Coríntios', imageId: '1-corintios' },
  { id: '2-corintios', title: '2 Coríntios', imageId: '2-corintios' },
  { id: 'galatas', title: 'Gálatas', imageId: 'galatas' },
  { id: 'romanos', title: 'Romanos', imageId: 'romanos' },
  { id: 'colossenses', title: 'Colossenses', imageId: 'colossenses' },
  { id: 'efesios', title: 'Efésios', imageId: 'efesios' },
  { id: 'filemom', title: 'Filemom', imageId: 'filemom' },
  { id: 'filipenses', title: 'Filipenses', imageId: 'filipenses' },
  { id: '1-timoteo', title: '1 Timóteo', imageId: '1-timoteo' },
  { id: 'tito', title: 'Tito', imageId: 'tito' },
  { id: '2-timoteo', title: '2 Timóteo', imageId: '2-timoteo' },
  { id: 'hebreus', title: 'Hebreus', imageId: 'hebreus' },
  { id: '1-pedro', title: '1 Pedro', imageId: '1-pedro' },
  { id: '2-pedro', title: '2 Pedro', imageId: '2-pedro' },
  { id: 'judas', title: 'Judas', imageId: 'judas' },
  { id: '1-joao', title: '1 João', imageId: '1-joao' },
  { id: '2-joao', title: '2 João', imageId: '2-joao' },
  { id: '3-joao', title: '3 João', imageId: '3-joao' },
  { id: 'apocalipse', title: 'Apocalipse', imageId: 'apocalipse' },
];
